#include "AtlasLabels.C"
#include "AtlasLabels.h"
void plot_hists_contour(TString timing, double tau, int hsbin, int hdbin, TString single_selection, TString di_selection) {
  TString name1, name2;
  name1 = "hist_"+timing+".root";
  name2 = "hist_unwt_"+timing+".root";
  TFile *f1 = TFile::Open(name1);
  TFile *f2 = TFile::Open(name2);

  TString hsbin_name, hdbin_name;
  hsbin_name.Form("hs%i",hsbin);
  hdbin_name.Form("hd%i",hdbin);

  TH2F *hs1 = (TH2F*)f1->Get(hsbin_name);
  TH2F *hd1 = (TH2F*)f1->Get(hdbin_name);
  TH2F *hs2 = (TH2F*)f2->Get(hsbin_name);
  TH2F *hd2 = (TH2F*)f2->Get(hdbin_name);

  TGraph *cont0 = NULL;
  TGraph *cont1 = NULL;
  TGraph *cont2 = NULL;
  TObjArray *conts0 = NULL;

  TCanvas *c1 = new TCanvas();
  hs1->GetXaxis()->SetTitle("m_{#tilde{g}} [GeV]");
  hs1->GetYaxis()->SetTitle("m_{#tilde{#chi}_{1}^{0}} [GeV]");
  hs1->GetYaxis()->SetRangeUser(100,2050);
  hs1->GetXaxis()->SetRangeUser(750,2200);
  hs1->SetMarkerSize(1.5);
  gStyle->SetPaintTextFormat("4.1f");
  hs1->SetContour(3);
  hs1->SetContourLevel(0,5);
  hs1->SetContourLevel(1,10);
  hs1->SetContourLevel(2,15);
  hs1->Draw("CONT LIST");
  c1->Update();
  conts0 = (TObjArray*)gROOT->GetListOfSpecials()->FindObject("contours");
  curv0 = (TGraph*)((TList*)conts0->At(0))->First();
  curv1 = (TGraph*)((TList*)conts0->At(1))->First();
  curv2 = (TGraph*)((TList*)conts0->At(2))->First();
  curv0->SetLineWidth(2);
  curv1->SetLineWidth(2);
  curv2->SetLineWidth(2);
  curv0->SetLineColor(1);
  curv1->SetLineColor(2);
  curv2->SetLineColor(3);
  hs1->Draw("axis");
  curv0->Draw("lsame");
  curv1->Draw("lsame");
  curv2->Draw("lsame");
  TLegend leg1(0.2, 0.7, 0.4, 0.8);
  leg1.SetLineColor(0);
  leg1.SetFillStyle(0);    
  leg1.SetTextSize(0.04);
  leg1.SetShadowColor(0);
  leg1.AddEntry(curv0,"5 Events","l");
  leg1.AddEntry(curv1,"10 Events","l");
  leg1.AddEntry(curv2,"15 Events","l");
  leg1.Draw();
  TLatex l;
  l.SetNDC();
  TString s;
  s.Form("Single Photon, #tau = %.1f, ",tau);
  s += single_selection;
  l.SetTextSize(0.04);
  l.DrawLatex(0.2,0.85,s);
  TString s2;
  s2 = "cutflow_contour_weighted_"+timing+"_single_SBT";
  c1->SaveAs(s2+".png");
  c1->SaveAs(s2+".pdf");
  c1->SaveAs(s2+".eps");
  c1->SaveAs(s2+".C");
  
  TCanvas *c2 =new TCanvas();
  hd1->GetXaxis()->SetTitle("m_{#tilde{g}} [GeV]");
  hd1->GetYaxis()->SetTitle("m_{#tilde{#chi}_{1}^{0}} [GeV]");
  hd1->GetYaxis()->SetRangeUser(100,2050);
  hd1->GetXaxis()->SetRangeUser(750,2200);
  hd1->SetMarkerSize(1.5);
  gStyle->SetPaintTextFormat("4.1f");
  hd1->SetContour(3);
  hd1->SetContourLevel(0,5);
  hd1->SetContourLevel(1,10);
  hd1->SetContourLevel(2,15);
  hd1->Draw("CONT LIST");
  c2->Update();
  conts0 = (TObjArray*)gROOT->GetListOfSpecials()->FindObject("contours");
  curv0 = (TGraph*)((TList*)conts0->At(0))->First();
  curv1 = (TGraph*)((TList*)conts0->At(1))->First();
  curv2 = (TGraph*)((TList*)conts0->At(2))->First();
  curv0->SetLineWidth(2);
  curv1->SetLineWidth(2);
  curv2->SetLineWidth(2);
  curv0->SetLineColor(1);
  curv1->SetLineColor(2);
  curv2->SetLineColor(3);
  hd1->Draw("axis");
  curv0->Draw("lsame");
  curv1->Draw("lsame");
  curv2->Draw("lsame");
  TLegend leg2(0.2, 0.7, 0.4, 0.8);
  leg2.SetLineColor(0);
  leg2.SetFillStyle(0);
  leg2.SetTextSize(0.04);
  leg2.SetShadowColor(0);
  leg2.AddEntry(curv0,"5 Events","l");
  leg2.AddEntry(curv1,"10 Events","l");
  leg2.AddEntry(curv2,"15 Events","l");
  leg2.Draw();
  l.SetNDC();
  s.Form("Diphoton, #tau = %.1f, ",tau);
  s += di_selection;
  l.SetTextSize(0.04);
  l.DrawLatex(0.2,0.85,s);
  s2 = "cutflow_contour_weighted_"+timing+"_di_SBT";
  c2->SaveAs(s2+".png");
  c2->SaveAs(s2+".pdf");
  c2->SaveAs(s2+".eps");
  c2->SaveAs(s2+".C");
  
  TCanvas *c3 =new TCanvas();
  hs2->GetXaxis()->SetTitle("m_{#tilde{g}} [GeV]");
  hs2->GetYaxis()->SetTitle("m_{#tilde{#chi}_{1}^{0}} [GeV]");
  hs2->GetYaxis()->SetRangeUser(100,2050);
  hs2->GetXaxis()->SetRangeUser(750,2200);
  hs2->SetMarkerSize(1.5);
  gStyle->SetPaintTextFormat("4.1f");
  hs2->SetContour(3);
  hs2->SetContourLevel(0,5);
  hs2->SetContourLevel(1,10);
  hs2->SetContourLevel(2,15);
  hs2->Draw("CONT LIST");
  c3->Update();
  conts0 = (TObjArray*)gROOT->GetListOfSpecials()->FindObject("contours");
  curv0 = (TGraph*)((TList*)conts0->At(0))->First();
  curv1 = (TGraph*)((TList*)conts0->At(1))->First();
  curv2 = (TGraph*)((TList*)conts0->At(2))->First();
  curv0->SetLineWidth(2);
  curv1->SetLineWidth(2);
  curv2->SetLineWidth(2);
  curv0->SetLineColor(1);
  curv1->SetLineColor(2);
  curv2->SetLineColor(3);
  hs2->Draw("axis");
  curv0->Draw("lsame");
  curv1->Draw("lsame");
  curv2->Draw("lsame");
  TLegend leg3(0.2, 0.7, 0.4, 0.8);
  leg3.SetLineColor(0);
  leg3.SetFillStyle(0);
  leg3.SetTextSize(0.04);
  leg3.SetShadowColor(0);
  leg3.AddEntry(curv0,"5 Events","l");
  leg3.AddEntry(curv1,"10 Events","l");
  leg3.AddEntry(curv2,"15 Events","l");
  leg3.Draw();
  l.SetNDC();
  s.Form("Single Photon, #tau = %.1f, ", tau);
  s += single_selection;
  l.SetTextSize(0.04);
  l.DrawLatex(0.2,0.85,s);
  s2 = "cutflow_contour_unwt_"+timing+"_single_SBT";
  c3->SaveAs(s2+".png");
  c3->SaveAs(s2+".pdf");
  c3->SaveAs(s2+".eps");
  c3->SaveAs(s2+".C");

  TCanvas *c4 =new TCanvas();
  hd2->GetXaxis()->SetTitle("m_{#tilde{g}} [GeV]");
  hd2->GetYaxis()->SetTitle("m_{#tilde{#chi}_{1}^{0}} [GeV]");
  hd2->GetYaxis()->SetRangeUser(100,2050);
  hd2->GetXaxis()->SetRangeUser(750,2200);
  hd2->SetMarkerSize(1.5);
  gStyle->SetPaintTextFormat("4.1f");
  hd2->SetContour(3);
  hd2->SetContourLevel(0,5);
  hd2->SetContourLevel(1,10);
  hd2->SetContourLevel(2,15);
  hd2->Draw("CONT LIST");
  c4->Update();
  conts0 = (TObjArray*)gROOT->GetListOfSpecials()->FindObject("contours");
  curv0 = (TGraph*)((TList*)conts0->At(0))->First();
  curv1 = (TGraph*)((TList*)conts0->At(1))->First();
  curv2 = (TGraph*)((TList*)conts0->At(2))->First();
  curv0->SetLineWidth(2);
  curv1->SetLineWidth(2);
  curv2->SetLineWidth(2);
  curv0->SetLineColor(1);
  curv1->SetLineColor(2);
  curv2->SetLineColor(3);
  hd2->Draw("axis");
  curv0->Draw("lsame");
  curv1->Draw("lsame");
  curv2->Draw("lsame");
  TLegend leg4(0.2, 0.7, 0.4, 0.8);
  leg4.SetLineColor(0);
  leg4.SetFillStyle(0);
  leg4.SetTextSize(0.04);
  leg4.SetShadowColor(0);
  leg4.AddEntry(curv0,"5 Events","l");
  leg4.AddEntry(curv1,"10 Events","l");
  leg4.AddEntry(curv2,"15 Events","l");
  leg4.Draw();
  l.SetNDC();
  s.Form("Diphoton, #tau = %.1f, ", tau);
  s += di_selection;
  l.SetTextSize(0.04);
  l.DrawLatex(0.2,0.85,s);
  s2 = "cutflow_contour_unwt_"+timing+"_di_SBT";
  c4->SaveAs(s2+".png");
  c4->SaveAs(s2+".pdf");
  c4->SaveAs(s2+".eps");
  c4->SaveAs(s2+".C");
  
}
